version: '3.7'
services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "cloud_file"
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
